[versions]
kotlin = "1.9.23"
intellij = "1.17.3"
grammarkit = "2021.2.2"
json = "20240303"
json-schema = "1.14.4"
commons-validator = "1.8.0"

[libraries]
org-json = { group = "org.json", name = "json", version.ref = "json" }
org-json-schema = { group = "com.github.everit-org.json-schema", name = "org.everit.json.schema", version.ref = "json-schema" }
commons-validator = { group = "commons-validator", name = "commons-validator", version.ref = "commons-validator" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-intellij = { id = "org.jetbrains.intellij", version.ref = "intellij" }
jetbrains-grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
